# INFO: Generates db/backfills/playlist_tracks_order_key.sql, a deterministic backfill for playlist_tracks.order_key; never connects to a database.

import logging
from pathlib import Path

from fractional_indexing import generate_n_keys_between

logger = logging.getLogger(__name__)

N = 10000

OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "db"
    / "backfills"
    / "playlist_tracks_order_key.sql"
)

_TRIGGER = "trg_bump_playlist_on_track_change"


def order_keys(n: int) -> list[str]:
    """Return n fractional-indexing keys, stable by prefix in n.

    generate_n_keys_between(None, None, n) is stable by prefix: the i-th
    key does not depend on n. Every key must be ASCII alphanumeric so it
    can be embedded in a SQL literal without escaping; a key that is not
    raises ValueError.
    """
    keys = generate_n_keys_between(None, None, n)
    for key in keys:
        if not (key.isascii() and key.isalnum()):
            raise ValueError(f"generated key is not ASCII alphanumeric: {key!r}")
    return keys


def render_sql(n: int) -> str:
    keys = order_keys(n)

    values_lines = []
    for position, key in enumerate(keys, start=1):
        suffix = "," if position < n else ""
        values_lines.append(f"    ({position}, '{key}'){suffix}")
    values_block = "\n".join(values_lines)

    header = f"""-- db/backfills/playlist_tracks_order_key.sql (#133)
--
-- GENERATED by scripts/generate_playlist_tracks_order_key_backfill.py.
-- Do not edit by hand: regenerate it by re-running that script.
--
-- This is not a migration: it is a data backfill, meant to be re-run on
-- purpose (the last run right before the stage that starts reading
-- order_key). Every run leaves each row with the order_key that matches
-- its current position, whether that row is untouched, was reordered
-- since the last run, or never had a key at all.
--
-- N = {n}. The lookup below covers position 1..{n}.
--
-- The before-every-run check and the after-run verification live in
-- db/backfills/README.md, not here.
--
-- {_TRIGGER} is disabled before the UPDATE and re-enabled before
-- COMMIT, both inside this transaction, so public.playlists.updated_at
-- does not move because of this backfill.
"""

    body = f"""BEGIN;

ALTER TABLE public.playlist_tracks DISABLE TRIGGER {_TRIGGER};

UPDATE public.playlist_tracks AS pt
  SET order_key = k.order_key
  FROM (VALUES
{values_block}
  ) AS k(position, order_key)
  WHERE pt.position = k.position
    AND pt.order_key IS DISTINCT FROM k.order_key;

ALTER TABLE public.playlist_tracks ENABLE TRIGGER {_TRIGGER};

DO $$
  BEGIN
    IF EXISTS (
      SELECT 1 FROM public.playlist_tracks WHERE order_key IS NULL
    ) THEN
      RAISE EXCEPTION 'playlist_tracks_order_key_backfill: found rows with order_key IS NULL';
    END IF;

    IF EXISTS (
      SELECT 1 FROM public.playlist_tracks
      GROUP BY playlist_id, order_key
      HAVING count(*) > 1
    ) THEN
      RAISE EXCEPTION 'playlist_tracks_order_key_backfill: found duplicate (playlist_id, order_key) pairs';
    END IF;

    IF EXISTS (
      SELECT 1 FROM (
        SELECT
          row_number() OVER (PARTITION BY playlist_id ORDER BY position) AS by_position,
          row_number() OVER (PARTITION BY playlist_id ORDER BY order_key COLLATE "C") AS by_key
        FROM public.playlist_tracks
      ) t
      WHERE by_position <> by_key
    ) THEN
      RAISE EXCEPTION 'playlist_tracks_order_key_backfill: order_key order does not match position order';
    END IF;
  END;
$$;

COMMIT;
"""

    return header + "\n" + body


def main(output: Path = OUTPUT) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_sql(N), encoding="utf-8", newline="\n")
    logger.info("wrote %s (N=%s)", output, N)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    main()
